"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, CalendarDays, CheckCheck, CircleCheck, Clock3, Eye, FileText, MailCheck, MousePointerClick, Plus, RefreshCw, Send, Upload, UserPlus, UserRoundCheck, UserRoundMinus, Users } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { ViewId } from "./data";
const fmt=(n:any)=>n==null?"—":Number(n).toLocaleString();
const rate=(n:number,d:number)=>d?`${(n/d*100).toFixed(1)}%`:"—";
const date=(v:string)=>v?new Date(v.includes("T")?v:v.replace(" ","T")+"Z").toLocaleDateString(undefined,{month:"short",day:"numeric"}):"—";
function Card({title,caption,action,children,className=""}:{title:string;caption?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`studio-panel min-w-0 overflow-hidden ${className}`}><div className="flex items-start justify-between gap-2 px-4 pb-3 pt-4"><div><h3 className="text-sm font-bold text-[#26365b]">{title}</h3>{caption&&<p className="mt-1 text-xs text-[#8993a7]">{caption}</p>}</div>{action}</div>{children}</section>;}
function Empty({children}:{children:ReactNode}){return <div className="flex min-h-36 items-center justify-center px-5 py-8 text-center text-sm leading-6 text-slate-400">{children}</div>;}
export function DashboardView({workspace,updateWorkspace,workspaceError,changeView,openNewsletter,importCsv}:{workspace:any;updateWorkspace:(p:any)=>Promise<void>;workspaceError:string;changeView:(v:ViewId)=>void;openNewsletter:(id?:string)=>void;importCsv:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[detail,setDetail]=useState<"links"|"content"|null>(null);
 const campaignId=workspace?.campaign?.id||"",from=workspace?.preferences.from||"",to=workspace?.preferences.to||"";
 const [revision,setRevision]=useState(0);
 useEffect(()=>{if(!workspace)return;const controller=new AbortController();setData(null);setError("");fetch(`/api/dashboard?${new URLSearchParams({campaignId,from,to})}`,{signal:controller.signal}).then(async r=>{const d:any=await r.json();if(!r.ok)throw new Error(d.error||"Could not load dashboard");setData(d);}).catch(e=>{if(e.name!=="AbortError")setError(e.message);});return()=>controller.abort();},[campaignId,from,to,revision,!!workspace]);
 async function refresh(){setBusy(true);setError("");try{if(campaignId){const r=await fetch(`/api/analytics?campaignId=${encodeURIComponent(campaignId)}`);const d:any=await r.json();if(!r.ok||d.error)throw new Error(d.error||"Could not refresh campaign statistics");}setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Refresh failed");}finally{setBusy(false);}}
 const m=data?.metrics||{},audience=data?.audience||{},funnel=[{label:"Sent",value:m.sent,color:"#249e64",Icon:Send},{label:"Delivered",value:m.delivered,color:"#175cdf",Icon:MailCheck},{label:"Opened",value:m.opened,color:"#8060c5",Icon:Eye},{label:"Clicked",value:m.clicked,color:"#ef922f",Icon:MousePointerClick},{label:"RSVPs",value:m.rsvps,color:"#16a2b0",Icon:CircleCheck},{label:"Confirmed",value:m.confirmed,color:"#1b9d64",Icon:UserRoundCheck}];
 const stats=[...funnel.slice(0,4),funnel[5],funnel[4],{label:"Awaiting response",value:data?Math.max(0,m.rsvps-m.confirmed):null,color:"#d88928",Icon:Clock3}];
 const action=(label:string,fn:()=>void)=><button onClick={fn} className="shrink-0 text-xs font-semibold text-[#175cdf] hover:underline">{label}</button>;
 const links=data?.topLinks||[];
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-[#182747]">Jai Shri Mataji{workspace?.user.firstName?`, ${workspace.user.firstName}`:""}!</h1><p className="mt-1 text-sm text-[#7d889e]">Welcome to Sahaja Yoga Newsletter Studio.</p></div><div className="flex gap-2"><Button variant="outline" onClick={importCsv}><Upload/>Upload CSV</Button><Button onClick={()=>openNewsletter()} className="bg-[#155bd7]"><Plus/>Create newsletter</Button></div></div>
  {(error||workspaceError)&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error||workspaceError}</p>}
  {data?.sampleAnalytics && <p className="rounded-xl border border-teal-200 bg-teal-50/80 px-4 py-2 text-xs font-medium text-teal-800">Sample analytics · illustrative campaign results and audience figures for exploring the studio.</p>}
  <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_280px] 2xl:grid-cols-[minmax(0,1fr)_300px]">
   <div className="min-w-0 space-y-4">
    <section className="studio-panel p-4"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-wide text-[#68748d]">Current campaign</span><Select value={campaignId} onValueChange={v=>{void updateWorkspace({campaignId:v}).catch(e=>setError(e.message));}}><SelectTrigger aria-label="Current campaign" className="h-8 max-w-[360px] flex-1 border-0 bg-transparent text-sm font-bold shadow-none"><SelectValue placeholder="No campaign in this period"/></SelectTrigger><SelectContent>{workspace?.campaigns?.map((c:any)=><SelectItem key={c.id} value={c.id}>{c.title}</SelectItem>)}</SelectContent></Select><Badge className="bg-[#e8f7ee] text-[#238756]">{workspace?.campaign?.status||"No campaign"}</Badge><Button variant="ghost" size="icon-sm" disabled={busy} onClick={refresh} aria-label="Refresh campaign statistics"><RefreshCw className={busy?"animate-spin":""}/></Button></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 2xl:grid-cols-7">{stats.map(({label,value,color,Icon})=><div key={label} className={`rounded-xl border p-3 ${label==="Confirmed"?"border-[#249d67] bg-gradient-to-br from-[#29ae76] to-[#148d57] text-white shadow-[0_5px_16px_#20a46825]":"border-[#edf0f5] bg-white"}`}><div className="flex items-center gap-2"><Icon className="size-5 shrink-0" style={{color:label==="Confirmed"?"#b9f2d3":color}}/><span className="text-xs font-semibold leading-4">{label}</span></div><p className="my-3 text-[27px] font-bold tracking-tight">{fmt(value)}</p><p className={`text-xs ${label==="Confirmed"?"text-white/75":"text-[#8a94a8]"}`}>{label==="Awaiting response"?"Pending RSVP records":label==="Opened"?"Unique tracked readers":label==="Clicked"?"Unique tracked clickers":label==="Delivered"?"Sent less recorded bounces":"Campaign lifetime"}</p></div>)}</div></section>
    <div className="grid gap-4 lg:grid-cols-3">
     <Card title="Engagement funnel" caption={workspace?.campaign?.title||"Select a saved campaign"}><div className="space-y-2 px-4 pb-4">{funnel.map((f,i)=><div key={f.label} className="flex items-center gap-2"><div className="flex h-7 w-[40%] items-center justify-center text-xs font-bold text-white" style={{background:f.color,clipPath:`polygon(${i*5}% 0,${100-i*5}% 0,${95-i*5}% 100%,${i*5+5}% 100%)`}}>{fmt(f.value)}</div><span className="min-w-0 flex-1 text-xs text-slate-500">{f.label}</span><b className="text-xs text-slate-600">{rate(f.value,m.sent)}</b></div>)}</div></Card>
     <Card title="RSVP trend" caption={data?.sampleAnalytics?"Cumulative confirmed RSVPs":"New responses in selected period"} action={<span className="text-xl font-bold text-[#249d67]">{fmt(m.confirmed)}</span>}>{data?.trend.length?<div className="h-52 pr-3"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.trend} margin={{left:-22,bottom:8}}><CartesianGrid vertical={false} stroke="#eef1f6"/><XAxis dataKey="day" tickFormatter={v=>v.slice(5)} tick={{fontSize:12}} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Line type="monotone" dataKey="rsvps" name={data?.sampleAnalytics?"Confirmed":"Responses"} stroke="#29a168" strokeWidth={2} dot={{r:3}}/></LineChart></ResponsiveContainer></div>:<Empty>Confirmed and pending RSVP records will build this timeline.</Empty>}</Card>
     <Card title="Subscriber engagement" caption="One group per recipient">{data?.engagement.some((p:any)=>p.value)?<><div className="h-36"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.engagement} dataKey="value" nameKey="name" innerRadius={40} outerRadius={62} paddingAngle={2}>{data.engagement.map((p:any)=><Cell key={p.name} fill={p.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="space-y-2 px-4 pb-4">{data.engagement.map((p:any)=><div key={p.name} className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full" style={{background:p.color}}/><span className="flex-1 text-slate-500">{p.name}</span><b>{fmt(p.value)}</b></div>)}</div></>:<Empty>Reader and click activity will appear after sending and syncing.</Empty>}</Card>
    </div>
    <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-[1.2fr_1fr_1fr]">
     <Card title="Audience overview" caption={data?.sampleAnalytics?"Illustrative audience · six-month overview":"Your saved subscriber list"} action={action("View all",()=>changeView("subscribers"))}><div className="grid grid-cols-2 gap-2 px-4">{[{label:"Total subscribers",value:audience.total,Icon:Users,color:"#20a56b"},{label:"Active subscribers",value:audience.active,Icon:CheckCheck,color:"#ed9a30"},{label:"New in period",value:audience.newSubscribers,Icon:UserPlus,color:"#4b7ce4"},{label:"Unsubscribed",value:audience.unsubscribed,Icon:UserRoundMinus,color:"#e76891"}].map(a=><div key={a.label} className="flex items-center gap-2 rounded-lg bg-[#f8fafd] p-2"><a.Icon className="size-4 shrink-0" style={{color:a.color}}/><div><p className="text-xs text-slate-500">{a.label}</p><b className="text-sm">{fmt(a.value)}</b></div></div>)}</div><p className="px-4 pt-4 text-xs font-semibold text-slate-500">{data?.sampleAnalytics?"Subscriber growth · last six months":"New subscribers by month"}</p>{data?.growth.length?<div className="h-40 px-2"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.growth} margin={{left:-22,right:8,bottom:6}}><defs><linearGradient id="audience-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#24aa71" stopOpacity={.2}/><stop offset="100%" stopColor="#24aa71" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="month" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="total" name={data?.sampleAnalytics?"Total subscribers":"New subscribers"} stroke="#24aa71" fill="url(#audience-fill)"/></AreaChart></ResponsiveContainer></div>:<Empty>Import your subscriber list to see audience growth.</Empty>}</Card>
     <Card title="Top links clicked" caption="Tracked links in this newsletter" action={action("Full report",()=>setDetail("links"))}>{links.length?<div className="space-y-4 px-4 pb-4"><div className="flex justify-between text-xs text-slate-400"><span>Link</span><span>Clicks · unique CTR</span></div>{links.slice(0,5).map((l:any)=><div key={l.id}><div className="mb-2 flex items-start justify-between gap-2 text-xs"><span className="line-clamp-2 font-semibold text-slate-600">{l.label}</span><span className="shrink-0 text-slate-500">{fmt(l.clicks)} · {rate(l.people,m.delivered||m.sent)}</span></div><div className="h-1.5 rounded-full bg-blue-50"><div className="h-full rounded-full bg-[#175cdf]" style={{width:`${links[0].clicks?l.clicks/links[0].clicks*100:0}%`}}/></div></div>)}</div>:<Empty>Save a newsletter with album or booking links to see their performance here.</Empty>}</Card>
     <Card title="Content performance" caption="Clicks attributed to linked content" action={action("Details",()=>setDetail("content"))} className="lg:col-span-2 2xl:col-span-1">{data?.content.length?<div className="space-y-3 px-4 pb-4">{data.content.slice(0,5).map((c:any)=><div key={c.id} className="flex items-center gap-3">{c.image?<img src={c.image} alt="" className="h-10 w-12 shrink-0 rounded-md object-cover"/>:<div className="flex h-10 w-12 shrink-0 items-center justify-center rounded-md bg-blue-50"><FileText className="size-4 text-blue-500"/></div>}<div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-600">{c.title}</p><p className="mt-1 text-xs text-slate-400">{c.clicks==null?"No tracked link":"Link clicks: "+fmt(c.clicks)}</p></div></div>)}</div>:<Empty>Linked stories and galleries from the selected newsletter will appear here.</Empty>}</Card>
    </div>
    <Card title="Historical campaign performance" caption="Campaigns in your selected period" action={action("View all campaigns",()=>changeView("newsletters"))}><div className="overflow-x-auto"><Table><TableHeader><TableRow>{["Campaign","Sent","Opens","Clicks","Confirmed","Date","Status"].map(h=><TableHead key={h} className="text-xs">{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.history.map((c:any)=><TableRow key={c.id}><TableCell><button onClick={()=>openNewsletter(c.id)} className="max-w-56 truncate text-left text-xs font-semibold text-[#29436c] hover:text-blue-600">{c.title}</button></TableCell><TableCell>{fmt(c.sent)}</TableCell><TableCell>{fmt(c.opened)}</TableCell><TableCell>{fmt(c.clicked)}</TableCell><TableCell>{fmt(c.confirmed)}</TableCell><TableCell className="whitespace-nowrap text-xs">{date(c.sentAt||c.updatedAt)}</TableCell><TableCell><Badge className="bg-[#edf7f1] text-[#398565]">{c.status}</Badge></TableCell></TableRow>)}</TableBody></Table></div>{!data?.history.length&&<Empty>Your saved newsletters will appear here. Choose a wider date range to see older editions.</Empty>}</Card>
   </div>
   <aside className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1">
    <Card title="Upcoming events" action={action("View all",()=>changeView("events"))}>{data?.upcoming.length?<div className="divide-y divide-slate-100 px-3 pb-3">{data.upcoming.slice(0,5).map((e:any)=><button key={e.id} onClick={()=>changeView("events")} className="flex w-full items-center gap-3 rounded-lg px-1 py-4 text-left hover:bg-blue-50"><img src={e.imageUrl||"/images/collective-meditation.jpg"} onError={ev=>{ev.currentTarget.onerror=null;ev.currentTarget.src="/images/collective-meditation.jpg";}} alt={e.title} className="event-photo h-16 w-[76px] shrink-0 rounded-xl object-cover"/><span className="min-w-0 flex-1"><b className="line-clamp-2 text-xs leading-5 text-[#2f3e5f]">{e.title}</b><span className="mt-1 block truncate text-xs text-slate-400">{e.location}</span></span><span className="max-w-12 text-center text-xs font-semibold text-slate-500">{date(e.startsAt)}</span></button>)}</div>:<Empty>Add upcoming events to keep your next newsletter on track.</Empty>}</Card>
    <Card title="Recent newsletters" action={action("View all",()=>changeView("newsletters"))}>{data?.history.length?<div className="space-y-1 px-3 pb-3">{data.history.slice(0,6).map((c:any)=><button key={c.id} onClick={()=>openNewsletter(c.id)} className="flex w-full items-start gap-2 rounded-lg p-2 text-left hover:bg-blue-50"><FileText className="mt-1 size-4 shrink-0 text-slate-500"/><div className="min-w-0 flex-1"><p className="line-clamp-2 text-xs font-semibold text-slate-600">{c.title}</p><p className="mt-1 text-xs text-slate-400">{date(c.updatedAt)}</p></div><span className="rounded bg-green-50 px-1.5 py-1 text-xs text-green-700">{c.status}</span></button>)}</div>:<Empty>Your first saved edition will appear here.</Empty>}</Card>
   </aside>
  </div>
  <p className="text-xs leading-5 text-slate-400">{data?.sampleAnalytics?"Illustrative sample data. No emails have been sent from this preview. ":data?.syncedAt?`Last Sender sync: ${new Date(data.syncedAt).toLocaleString()}. `:"Showing saved workspace records. "}Open tracking is approximate. Booking-link clicks measure interest; confirmed RSVPs require a recorded response.</p>
  <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{detail==="links"?"Link performance":"Content performance"}</DialogTitle><DialogDescription>{workspace?.campaign?.title||"Select a campaign"} · campaign lifetime totals</DialogDescription></DialogHeader>{(detail==="links"?links:data?.content||[]).map((item:any)=><div key={item.id} className="rounded-xl border p-4"><p className="font-semibold">{item.label||item.title}</p><p className="mt-1 text-sm text-slate-500">{item.clicks==null?"This block has no tracked link":`${fmt(item.clicks)} clicks`}</p>{item.url&&<p className="mt-2 break-all text-xs text-blue-600">{item.url}</p>}</div>)}</DialogContent></Dialog>
 </div>;
}
