"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import { CalendarDays, CheckCircle2, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type EventData = { id: string; title: string; description: string; startsAt: string; location: string };

export default function RsvpPage({ params }: { params: Promise<{ eventId: string }> }) {
  const [eventId, setEventId] = useState(""); const [event, setEvent] = useState<EventData | null>(null); const [email, setEmail] = useState(""); const [guestCount, setGuestCount] = useState(0); const [status, setStatus] = useState("confirmed"); const [done, setDone] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void params.then(({ eventId: id }) => { setEventId(id); fetch(`/api/rsvp/${id}`).then((response) => response.json()).then((data: any) => setEvent(data.event || null)); }); }, [params]);
  const submit = async () => { const query = new URLSearchParams(window.location.search); const response = await fetch(`/api/rsvp/${eventId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, guestCount, status, uniqueId: query.get("u"), campaignId: query.get("c") }) }); const data = await response.json() as any; if (!response.ok) return setMessage(data.error || "Could not save your response"); setMessage(data.message); setDone(true); };
  if (!event) return <main className="flex min-h-screen items-center justify-center bg-[#f4f6fb] p-6 text-[#17213f]">Loading invitation…</main>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#edf3ff,#f7f8fb_45%)] p-5 text-[#17213f]"><div className="mx-auto max-w-2xl overflow-hidden rounded-3xl border border-[#e2e6ef] bg-white shadow-[0_24px_80px_rgba(31,46,86,.14)]"><div className="bg-gradient-to-br from-[#17275d] to-[#175cdf] p-8 text-white sm:p-12"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#ffd08c]">Sahaja Yoga · Invitation</p><h1 className="mt-4 font-serif text-4xl font-semibold leading-tight sm:text-5xl">{event.title}</h1><p className="mt-4 max-w-xl text-base leading-7 text-white/75">{event.description}</p></div><div className="p-6 sm:p-10">{done ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto size-14 text-[#19a566]"/><h2 className="mt-5 font-serif text-3xl font-semibold">{message}</h2><p className="mt-3 text-[#6e7990]">Thank you. We look forward to meditating together.</p></div> : <><div className="grid gap-3 rounded-2xl bg-[#f4f7fd] p-4 sm:grid-cols-2"><p className="flex items-center gap-2 text-sm font-semibold"><CalendarDays className="size-4 text-[#175cdf]"/>{new Date(event.startsAt).toLocaleString()}</p><p className="flex items-center gap-2 text-sm font-semibold"><MapPin className="size-4 text-[#175cdf]"/>{event.location || "Details by email"}</p></div><div className="mt-6"><Label htmlFor="email">Email address</Label><Input id="email" type="email" className="mt-2" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.org"/></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="response">Your response</Label><select id="response" value={status} onChange={(e) => setStatus(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="confirmed">Yes, I will join</option><option value="maybe">Maybe</option><option value="declined">I cannot join</option></select></div><div><Label htmlFor="guests">Additional guests</Label><Input id="guests" type="number" min="0" max="10" className="mt-2" value={guestCount} onChange={(e) => setGuestCount(Number(e.target.value))}/></div></div>{message && <p className="mt-4 text-sm text-red-600">{message}</p>}<Button onClick={submit} className="mt-6 w-full" size="lg">Save my response</Button><p className="mt-4 text-center text-xs leading-5 text-[#8a94a8]">Your response is used only to organize this gathering.</p></>}</div></div></main>;
}
